#+SETUPFILE: ../css/level-1.orgcss
#+TITLE: openstack havana all-in-one部署
#+DATE: 2014-01-07 10:38
#+OPTIONS: ^:{}
* 修改记录
|       时间 | 内容                             |
|------------+----------------------------------|
| 2014.01.07 | nova.conf和l3-agent firewall配置 |
* 部署环境
64位ubuntu-12.04.1-server系统 \\
双网卡
+ 外网eth0 192.168.60.108/24
+ 内网eth1 172.16.0.254/24
双硬盘
* 初始网卡配置
为eth0和eth1配置IP
#+BEGIN_SRC sh
# cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
address 192.168.60.108
netmask 255.255.255.0
gateway 192.168.60.1
dns-nameservers 8.8.8.8

auto eth1
iface eth1 inet static
        address 172.16.0.254
        netmask 255.255.255.0
#+END_SRC
重启网络
#+BEGIN_SRC sh
/etc/init.d/networking restart
#+END_SRC
* 添加havana源
#+BEGIN_SRC sh
apt-get install python-software-properties
add-apt-repository cloud-archive:havana
apt-get update && apt-get dist-upgrade
reboot
#+END_SRC
* 安装mysql和rabbitmq
#+BEGIN_SRC sh
#设置mysql root用户密码为123456
echo mysql-server-5.5 mysql-server/root_password password 123456 | debconf-set-selections
echo mysql-server-5.5 mysql-server/root_password_again password 123456 | debconf-set-selections
apt-get install mysql-server mysql-client python-mysqldb
#允许外部访问mysql
sed -i -e  "s/^\(bind-address\s*=\).*/\1 0.0.0.0/" /etc/mysql/my.cnf
#+END_SRC
** 创建数据库
数据库名称为各组件名字，密码与数据库名相同。
#+BEGIN_SRC sh
#进入mysql
mysql -u root -p123456
CREATE DATABASE keystone;
CREATE DATABASE glance;
CREATE DATABASE nova;
CREATE DATABASE cinder;
CREATE DATABASE neutron;
CREATE DATABASE heat;

GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY 'keystone';
GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY 'keystone';

GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY 'glance';
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY 'glance';

GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY 'nova';
GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY 'nova';

GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost' IDENTIFIED BY 'cinder';
GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%' IDENTIFIED BY 'cinder';

GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY 'neutron';
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY 'neutron';

GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'localhost' IDENTIFIED BY 'heat';
GRANT ALL PRIVILEGES ON heat.* TO 'heat'@'%' IDENTIFIED BY 'heat';
#+END_SRC
#重启mysql服务
#+BEGIN_SRC sh
/etc/init.d/mysql restart
#+END_SRC
** 安装rabbitmq
#+BEGIN_SRC sh
apt-get install rabbitmq-server
#+END_SRC
rabbitmq-server默认会创建一个用户，用户名密码均为guest，并允许任何人用guest用户和默认密码访问RabbitMQ server。
如果需要可以修改guest密码,命令:
#+BEGIN_SRC sh
rabbitmqctl change_password guest NEW_PASS
#+END_SRC
* 安装和配置Keystone
** 安装
#+BEGIN_SRC sh
apt-get install keystone
#+END_SRC
** 删除默认keystone的sqlite db 文件
#+BEGIN_SRC sh
rm -f /var/lib/keystone/keystone.db
#+END_SRC
** 配置openssl
在keystone与OpenStack服务之间如果要使用ssl进行token认证,就需要使用到openssl
#+BEGIN_SRC sh
openssl rand -hex 10
cdccc11cf024bd7de58e
#+END_SRC
** 修改配置文件
*** 修改/etc/keystone/keystone.conf
修改[DEFAULT]admin_token值， 修改[sql]的connection.
#+BEGIN_SRC sh
[DEFAULT]
admin_token = cdccc11cf024bd7de58e
[sql]
# The SQLAlchemy connection string used to connect to the database
connection = mysql://keystone:keystone@172.16.0.254/keystone
#+END_SRC
*** 同步keystone表数据到db中并重启keystone
#+BEGIN_SRC sh
keystone-manage db_sync
/etc/init.d/keystone restart
#+END_SRC
** 创建tenant、user、roles
*** 首先创建两个环境变量
#+BEGIN_SRC sh
export OS_SERVICE_TOKEN=cdccc11cf024bd7de58e
export OS_SERVICE_ENDPOINT=http://172.16.0.254:35357/v2.0
#+END_SRC
***  创建admin和service两个租户
#+BEGIN_SRC sh
keystone tenant-create --name=admin --description="Admin Tenant"
keystone tenant-create --name=service --description="Service Tenant"
#+END_SRC
*** 创建用户admin，密码password 
#+BEGIN_SRC sh
keystone user-create --name=admin --pass=password --email=admin@example.com
#+END_SRC
*** 创建角色admin
#+BEGIN_SRC sh
keystone role-create --name=admin
#+END_SRC
*** 关联用户、角色、租户
#+BEGIN_SRC sh
keystone user-role-add --user=admin --tenant=admin --role=admin
#+END_SRC
** 创建Services 及 API endpoints
首先创建一个类型为identity的keystone服务，名称为keystone：
#+BEGIN_SRC sh
keystone_id=$(keystone service-create --name=keystone --type=identity \
--description="Keystone Identity Service" | awk '/ id / { print $4 }')
#+END_SRC
创建endpoint
#+BEGIN_SRC sh
keystone endpoint-create \
--service-id=$keystone_id \
--publicurl=http://172.16.0.254:5000/v2.0 \
--internalurl=http://172.16.0.254:5000/v2.0 \
--adminurl=http://172.16.0.254:35357/v2.0
#+END_SRC
** 验证认证服务(Keystone)安装是否成功
先unset之前的环境变量：
#+BEGIN_SRC sh
unset OS_SERVICE_TOKEN OS_SERVICE_ENDPOINT
#+END_SRC
创建keystonerc文件(环境变量)
#+BEGIN_SRC sh
cat > /root/openrc.sh << _EOF_
export OS_USERNAME=admin
export OS_PASSWORD=password
export OS_TENANT_NAME=admin
export OS_AUTH_URL=http://172.16.0.254:35357/v2.0
_EOF_
echo 'source /root/openrc.sh' >> /root/.bashrc
source /root/openrc.sh
#+END_SRC
验证keystone是否正常
#+BEGIN_SRC sh
keystone token-get
keystone user-list
keystone role-list
keystone tenant-list
keystone endpoint-list
#+END_SRC
* 安装和配置glance
** 安装
#+BEGIN_SRC sh
apt-get install glance python-glanceclient sheepdog
#+END_SRC
删除 glance sqlite 文件：
#+BEGIN_SRC sh
rm -f /var/lib/glance/glance.sqlite
#+END_SRC
** 修改glance配置文件
修改/etc/glance/glance-api.conf
#+BEGIN_SRC sh
verbose = True
debug = True
sql_connection = mysql://glance:glance@172.16.0.254/glance

notifier_strategy = rabbit
rabbit_host = 172.16.0.254
rabbit_password = guest

[keystone_authtoken]
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
admin_tenant_name = service
admin_user = glance
admin_password = glance
#+END_SRC
修改/etc/glance/glance-registry.conf
#+BEGIN_SRC sh
verbose = True
debug = True
sql_connection = mysql://glance:glance@172.16.0.254/glance
[keystone_authtoken]
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
admin_tenant_name = service
admin_user = glance
admin_password = glance
#+END_SRC
/etc/glance/glance-api-paste.ini
#+BEGIN_SRC sh
[filter:authtoken]
paste.filter_factory=keystoneclient.middleware.auth_token:filter_factory
auth_host=172.16.0.254
admin_user=glance
admin_tenant_name=service
admin_password=glance
flavor=keystone
#+END_SRC
/etc/glance/glance-registry-paste.ini
#+BEGIN_SRC sh
[filter:authtoken]
paste.filter_factory=keystoneclient.middleware.auth_token:filter_factory
auth_host=172.16.0.254
admin_user=glance
admin_tenant_name=service
admin_password=glance
flavor=keystone
#+END_SRC
** 同步数据库
#+BEGIN_SRC sh
glance-manage db_sync
#+END_SRC
** 创建名为glance的认证用户
#+BEGIN_SRC sh
keystone user-create --name=glance --pass=glance --email=glance@example.com
keystone user-role-add --user=glance --tenant=service --role=admin
#+END_SRC
** 创建service服务和endpoint
#+BEGIN_SRC sh
glance_id=$(keystone service-create --name=glance --type=image \
--description="Glance Image Service" | awk '/ id / { print $4 }')

keystone endpoint-create \
--service-id=$glance_id \
--publicurl=http://172.16.0.254:9292 \
--internalurl=http://172.16.0.254:9292 \
--adminurl=http://172.16.0.254:9292
#+END_SRC
** 重启glance服务
#+BEGIN_SRC sh
service glance-registry restart
service glance-api restart
#+END_SRC
** 上传镜像
下载测试镜像
#+BEGIN_SRC sh
wget http://cdn.download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img
#+END_SRC
上传
#+BEGIN_SRC sh
glance image-create --name='cirros' --is-public true --container-format bare --disk-format qcow2 < ./cirros-0.3.0-x86_64-disk.img
#+END_SRC
查看上传的镜像
#+BEGIN_SRC sh
glance image-list
#+END_SRC
* 安装和配置nova
** 安装计算服务
#+BEGIN_SRC sh
apt-get install nova-novncproxy novnc nova-api python-novaclient \
nova-ajax-console-proxy nova-cert nova-conductor \
nova-consoleauth nova-doc nova-scheduler
apt-get install nova-compute-kvm python-guestfs
#+END_SRC
安装过程会提示你,选择”yes”即可。
** 修复guestfs的一个bug
#+BEGIN_SRC sh
chmod 0644 /boot/vmlinuz*
#+END_SRC
** 删除默认nova的sqlite db文件
#+BEGIN_SRC sh
rm -f /var/lib/nova/nova.sqlite
#+END_SRC
** 修改配置文件
修改/etc/nova/nova.conf，原有基础上添加
#+BEGIN_SRC sh
[DEFAULT]
#vnc
my_ip=172.16.0.254
vnc_enabled=True
vncserver_listen=0.0.0.0
vncserver_proxyclient_address=172.16.0.254
novncproxy_base_url=http://192.168.60.108:6080/vnc_auto.html

#Messaging
rpc_backend = nova.rpc.impl_kombu
rabbit_host = 172.16.0.254
rabbit_password = guest

#Glance
glance_host = 172.16.0.254

#Auth
auth_strategy=keystone

#Nova Metadata
neutron_metadata_proxy_shared_secret = cdccc11cf024bd7de58e
service_neutron_metadata_proxy = true

#Ceilometer
instance_usage_audit=True
instance_usage_audit_period=hour
notify_on_state_change=vm_and_task_state
notification_driver=nova.openstack.common.notifier.rpc_notifier
notification_driver=ceilometer.compute.nova_notifier

#neutron
network_api_class=nova.network.neutronv2.api.API
neutron_url=http://172.16.0.254:9696
neutron_auth_strategy=keystone
neutron_admin_tenant_name=service
neutron_admin_username=neutron
neutron_admin_password=neutron
neutron_admin_auth_url=http://172.16.0.254:35357/v2.0
#如果没有libvirt_vif_driver将不会有qvb等设备
libvirt_vif_driver = nova.virt.libvirt.vif.LibvirtHybridOVSBridgeDriver
linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver
#firewall_driver=nova.virt.firewall.NoopFirewallDriver
firewall_driver=nova.virt.libvirt.firewall.IptablesFirewallDriver
security_group_api=neutron

[database]
connection = mysql://nova:nova@172.16.0.254/nova

[keystone_authtoken]
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
admin_tenant_name = service
admin_user = nova
admin_password = nova

#+END_SRC
修改/etc/nova/api-paste.ini的[filter:authtoken]部分
#+BEGIN_SRC sh
[filter:authtoken]
paste.filter_factory = keystoneclient.middleware.auth_token:filter_factory
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
auth_uri = http://172.16.0.254:5000/v2.0
admin_tenant_name = service
admin_user = nova
admin_password = nova
#+END_SRC
** 创建用户与角色
#+BEGIN_SRC sh
keystone user-create --name=nova --pass=nova --email=nova@example.com
keystone user-role-add --user=nova --tenant=service --role=admin
#+END_SRC
** 创建service服务和endpoint
#+BEGIN_SRC sh
nova_id=$(keystone service-create --name=nova --type=compute \
--description="Nova Compute service" | awk '/ id / { print $4 }')

keystone endpoint-create \
--service-id=$nova_id \
--publicurl=http://172.16.0.254:8774/v2/%\(tenant_id\)s \
--internalurl=http://172.16.0.254:8774/v2/%\(tenant_id\)s \
--adminurl=http://172.16.0.254:8774/v2/%\(tenant_id\)s
#+END_SRC
** 重启nova服务
同步数据
#+BEGIN_SRC sh
nova-manage db sync
#+END_SRC
重启服务
#+BEGIN_SRC sh
cd /etc/init.d/; for i in $( ls nova-* ); do sudo service $i restart; done
#+END_SRC
#查看服务状态
#+BEGIN_SRC sh
nova-manage service list
Binary           Host                                 Zone             Status     State Updated_At
nova-cert        ubuntu                               internal         enabled    :-)   2013-12-24 05:39:29
nova-conductor   ubuntu                               internal         enabled    :-)   2013-12-24 05:39:27
nova-consoleauth ubuntu                               internal         enabled    :-)   2013-12-24 05:39:30
nova-compute     ubuntu                               nova             enabled    :-)   2013-12-24 05:39:27
nova-scheduler   ubuntu                               internal         enabled    :-)   2013-12-24 05:39:30
#+END_SRC
应该看到5个:)

测试nova是否安装正常
#+BEGIN_SRC sh
nova image-list
#+END_SRC
* Block Storage (Cinder)安装
** 安装服务
#+BEGIN_SRC sh
apt-get install cinder-api cinder-scheduler
#+END_SRC
** 建立一个逻辑卷卷组 cinder-volumes
创建一个普通分区，我这里用的sdb，创建了一个主分区，大小为所有空间
#+BEGIN_SRC sh
apt-get install cinder-volume lvm2
# fdisk /dev/sdb
n
p
1
Enter
Enter
t
8e
w
# pvcreate /dev/sdb1
# vgcreate cinder-volumes /dev/sdb1
# vgs
  VG             #PV #LV #SN Attr   VSize  VFree 
  cinder-volumes   1   0   0 wz--n- 10.00g 10.00g
  #+END_SRC
** 修改配置文件
/etc/cinder/cinder.conf，添加
#+BEGIN_SRC sh
sql_connection = mysql://cinder:cinder@172.16.0.254/cinder

rpc_backend = cinder.openstack.common.rpc.impl_kombu
rabbit_host = 172.16.0.254
rabbit_port = 5672
rabbit_userid = guest
rabbit_password = guest

control_exchange = cinder
notification_driver = cinder.openstack.common.notifier.rpc_notifier
#+END_SRC
/etc/cinder/api-paste.ini
#+BEGIN_SRC sh
[filter:authtoken]
paste.filter_factory=keystoneclient.middleware.auth_token:filter_factory
auth_host=172.16.0.254
auth_port = 35357
auth_protocol = http
admin_tenant_name = service
admin_user = cinder
admin_password = cinder
#+END_SRC
** 创建用户，角色，服务和endpoint
#+BEGIN_SRC sh
keystone user-create --name=cinder --pass=cinder --email=cinder@example.com
keystone user-role-add --user=cinder --tenant=service --role=admin

cinder_id1=$(keystone service-create --name=cinder --type=volume \
--description="Cinder Volume Service" | awk '/ id / { print $4 }')
keystone endpoint-create \
--service-id=$cinder_id1 \
--publicurl=http://172.16.0.254:8776/v1/%\(tenant_id\)s \
--internalurl=http://172.16.0.254:8776/v1/%\(tenant_id\)s \
--adminurl=http://172.16.0.254:8776/v1/%\(tenant_id\)s

cinder_id2=$(keystone service-create --name=cinder --type=volumev2 \
--description="Cinder Volume Service V2" | awk '/ id / { print $4 }')
keystone endpoint-create \
--service-id=$cinder_id2 \
--publicurl=http://172.16.0.254:8776/v2/%\(tenant_id\)s \
--internalurl=http://172.16.0.254:8776/v2/%\(tenant_id\)s \
--adminurl=http://172.16.0.254:8776/v2/%\(tenant_id\)s
#+END_SRC
** 同步数据并重启服务
#+BEGIN_SRC sh
cinder-manage db sync
service cinder-scheduler restart
service cinder-api restart
service cinder-volume restart
service tgt restart
#+END_SRC
** 检查
#+BEGIN_SRC sh
cinder list #无输出
#+END_SRC
* 安装和配置neutron
** 创建用户，服务和endpoint
#+BEGIN_SRC sh
keystone user-create --name=neutron --pass=neutron --email=neutron@example.com
keystone user-role-add --user=neutron --tenant=service --role=admin

neutron_id=$(keystone service-create --name=neutron --type=network \
--description="OpenStack Networking Service" | awk '/ id / { print $4 }')
keystone endpoint-create \
--service-id $neutron_id \
--publicurl http://172.16.0.254:9696 \
--adminurl http://172.16.0.254:9696 \
--internalurl http://172.16.0.254:9696
#+END_SRC
** 安装网络服务
*** 安装neutron组件
#+BEGIN_SRC sh
apt-get install neutron-server neutron-dhcp-agent  neutron-l3-agent neutron-lbaas-agent
#+END_SRC
*** 打开ip_forward
编辑/etc/sysctl.conf
#+BEGIN_SRC sh
net.ipv4.ip_forward=1
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter=0
#+END_SRC
重启网络
#+BEGIN_SRC sh
sysctl -p
/etc/init.d/networking restart
#+END_SRC
*** 编辑配置文件
编辑/etc/neutron/neutron.conf 
#+BEGIN_SRC sh
[DEFAULT]
debug = True
verbose = True
allow_overlapping_ips = True

core_plugin = neutron.plugins.openvswitch.ovs_neutron_plugin.OVSNeutronPluginV2
service_plugins = neutron.plugins.services.agent_loadbalancer.plugin.LoadBalancerPlugin
service_plugins = neutron.services.firewall.fwaas_plugin.FirewallPlugin

api_paste_config = /etc/neutron/api-paste.ini

auth_strategy = keystone

rpc_backend = neutron.openstack.common.rpc.impl_kombu
rabbit_host = 172.16.0.254
rabbit_port = 5672
rabbit_userid = guest
rabbit_password = guest

[keystone_authtoken]
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
auth_url = http://172.16.0.254:35357/v2.0
admin_tenant_name = service
admin_user = neutron
admin_password = neutron

[database]
connection = mysql://neutron:neutron@172.16.0.254/neutron
#+END_SRC
编辑/etc/neutron/api-paste.ini
#+BEGIN_SRC sh
[filter:authtoken]
paste.filter_factory = keystoneclient.middleware.auth_token:filter_factory
auth_host=172.16.0.254
auth_uri=http://172.16.0.254:5000
admin_user=neutron
admin_tenant_name=service
admin_password=neutron
#+END_SRC
编辑/etc/neutron/dhcp_agent.ini
#+BEGIN_SRC sh
dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq
use_namespaces = True
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
#+END_SRC
编辑/etc/neutron/l3_agent.ini
#+BEGIN_SRC sh
auth_url = http://172.16.0.254:35357/v2.0
admin_tenant_name = service
admin_user = neutron
admin_password = neutron
metadata_ip = 172.16.0.254
use_namespaces = True
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
#+END_SRC
编辑/etc/neutron/metadata_agent.ini
#+BEGIN_SRC sh
[DEFAULT]
auth_url = http://172.16.0.254:5000/v2.0
auth_region = regionOne
admin_tenant_name = service
admin_user = neutron
admin_password = neutron
nova_metadata_ip = 172.16.0.254
metadata_proxy_shared_secret = cdccc11cf024bd7de58e
#+END_SRC
编辑/etc/neutron/lbaas_agent.ini
#+BEGIN_SRC sh
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
device_driver = neutron.services.loadbalancer.drivers.haproxy.namespace_driver.HaproxyNSDriver
#+END_SRC
创建/etc/neutron/fwaas_driver.ini
#+BEGIN_SRC sh
[fwaas]
driver = neutron.services.firewall.drivers.linux.iptables_fwaas.IptablesFwaasDriver
enabled = True
#+END_SRC
编辑/etc/init/neutron-l3-agent 补充--config file fwaas_driver.ini
#+BEGIN_SRC sh
exec start-stop-daemon --start --chuid neutron --exec /usr/bin/neutron-l3-agent -- --config-file=/etc/neutron/neutron.conf --config-file=/etc/neutron/l3_agent.ini --config-file /etc/neutron/fwaas_driver.ini --log-file=/var/log/neutron/l3-agent.log
#+END_SRC
** 安装ovs插件
*** 安装
#+BEGIN_SRC sh
apt-get install openvswitch-datapath-dkms openvswitch-switch neutron-plugin-openvswitch-agent
service openvswitch-switch restart
#+END_SRC
*** 网络配置
**** 建立网桥
#+BEGIN_SRC sh
ovs-vsctl add-br br-int
ovs-vsctl add-br br-ex
ovs-vsctl add-port br-ex eth0
#+END_SRC
**** 编辑配置/etc/network/interfaces
#+BEGIN_SRC sh
auto lo
iface lo inet loopback

auto eth1
iface eth0 inet static
        address 172.16.0.254
        netmask 255.255.255.0

auto eth0
iface eth0 inet manual
        up ifconfig $IFACE 0.0.0.0 up
        down ifconfig $IFACE down

auto br-ex
iface br-ex inet static
        address 192.168.60.108
        netmask 255.255.255.0
        gateway 192.168.60.1
        dns-nameservers 8.8.8.8
#+END_SRC
**** 重启网络
#+BEGIN_SRC sh
ifconfig eth0 0
/etc/init.d/networking restart
#+END_SRC
*** 编辑配置文件
编辑/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
#+BEGIN_SRC sh
[securitygroup]
# Firewall driver for realizing neutron security group function.
firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
[ovs]
tenant_network_type = gre
tunnel_id_ranges = 1:1000
enable_tunneling = True
integration_bridge = br-int
tunnel_bridge = br-tun
local_ip = 172.16.0.254
#+END_SRC
** 重启服务
#+BEGIN_SRC sh
cd /etc/init.d/; for i in $( ls neutron-* ); do sudo service $i restart; done
#查看服务状态
neutron agent-list
+--------------------------------------+--------------------+--------+-------+----------------+
| id                                   | agent_type         | host   | alive | admin_state_up |
+--------------------------------------+--------------------+--------+-------+----------------+
| 6cc3719f-7c43-41c7-bc19-9839a362c321 | Open vSwitch agent | ubuntu | :-)   | True           |
| d96922b7-64a3-44f7-831f-1e9ea2033a33 | L3 agent           | ubuntu | :-)   | True           |
| ea701f27-1821-4134-9e6f-02acc8678e85 | DHCP agent         | ubuntu | :-)   | True           |
+--------------------------------------+--------------------+--------+-------+----------------+
#+END_SRC
* Orchestration Server(Heat)安装
** 安装
#+BEGIN_SRC sh
apt-get install heat-api heat-api-cfn heat-engine heat-api-cloudwatch
#+END_SRC
** 删除默认heat的sqlite db 文件
#+BEGIN_SRC sh
rm -f /var/lib/heat/heat.sqlite
#+END_SRC
** 编辑配置文件
/etc/heat/heat.conf
#+BEGIN_SRC sh
verbose = True
log_dir=/var/log/heat
rabbit_host = 172.16.0.254
rabbit_password = guest

# The SQLAlchemy connection string used to connect to the database
sql_connection = mysql://heat:heat@172.16.0.254/heat

[keystone_authtoken]
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
auth_uri = http://172.16.0.254:5000/v2.0
admin_tenant_name = service
admin_user = heat
admin_password = heat
[ec2_authtoken]
auth_uri = http://172.16.0.254:5000/v2.0
keystone_ec2_uri = http://172.16.0.254:5000/v2.0/ec2tokens
#+END_SRC
** 同步数据
#+BEGIN_SRC sh
heat-manage db_sync
#+END_SRC
** 创建用户和角色
#+BEGIN_SRC sh
keystone user-create --name=heat --pass=heat --email=heat@example.com
keystone user-role-add --user=heat --tenant=service --role=admin
#+END_SRC
** 创建服务和endpoint
#+BEGIN_SRC sh
heat_id=$(keystone service-create --name=heat --type=orchestration \
--description="Heat Orchestration API" | awk '/ id / { print $4 }')
keystone endpoint-create \
--service-id=$heat_id \
--publicurl=http://172.16.0.254:8004/v1/%\(tenant_id\)s \
--internalurl=http://172.16.0.254:8004/v1/%\(tenant_id\)s \
--adminurl=http://172.16.0.254:8004/v1/%\(tenant_id\)s

heat_cfn_id=$(keystone service-create --name=heat-cfn --type=cloudformation \
--description="Heat CloudFormation API" | awk '/ id / { print $4 }')
keystone endpoint-create \
--service-id=$heat_cfn_id \
--publicurl=http://172.16.0.254:8000/v1 \
--internalurl=http://172.16.0.254:8000/v1 \
--adminurl=http://172.16.0.254:8000/v1
#+END_SRC
** 重启服务
#+BEGIN_SRC sh
cd /etc/init.d/; for i in $( ls heat-* ); do sudo service $i restart; done
#+END_SRC
** 创建和管理stacks
#+BEGIN_SRC sh
wget https://raw.github.com/openstack/heat-templates/master/cfn/F17/WordPress_Composed_Instances.template
glance image-create --name F17-x86_64-cfntools --disk-format qcow2 --container-format bare --is-public True --copy-from http://fedorapeople.org/groups/heat/prebuilt-jeos-images/F17-x86_64-cfntools.qcow2
nova keypair-add heat_key > heat_key.priv
chmod 600 heat_key.priv
heat stack-create wordpress --template-file=WordPress_Composed_Instances.template --parameters="DBUsername=wp;DBPassword=wp;KeyName=userkey;LinuxDistribution=F17"
heat stack-list
#+END_SRC
PS:对heat还没有研究，创建stack是网上找的
* Metering/Monitoring Server（Ceilometer）安装
** 安装
安装服务
#+BEGIN_SRC sh
apt-get install ceilometer-api ceilometer-collector ceilometer-agent-central python-ceilometerclient ceilometer-agent-compute
#+END_SRC
安装MongoDB Orchestration 服务使用数据库来存储信息，此示例使用MongoDB数据库
#+BEGIN_SRC sh
apt-get install mongodb
#+END_SRC
** 创建数据库
运行mongo命令如果报错couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
#+BEGIN_SRC sh
mongod --repair
service mongodb restart
#+END_SRC
#+BEGIN_SRC sh
mongo
> use ceilometer
> db.addUser( { user: "ceilometer",
pwd: "ceilometer",
roles: [ "readWrite", "dbAdmin" ]
} )
#+END_SRC
编辑/etc/mongodb.conf
#+BEGIN_SRC sh
bind_ip=0.0.0.0
#+END_SRC
重启数据库
#+BEGIN_SRC sh
service mongodb restart
#+END_SRC
** 修改配置文件
修改/etc/ceilometer/ceilometer.conf
#+BEGIN_SRC sh
[DEFAULT]
http_control_exchanges=nova
http_control_exchanges=glance
http_control_exchanges=neutron
http_control_exchanges=cinder
auth_strategy=keystone
nova_control_exchange=nova
glance_control_exchange=glance
neutron_control_exchange=neutron
lock_path= /var/lock/ceilometer
state_path = /var/lib/ceilometer
debug=True
verbose= True
log_file= ceilometer.log
log_dir= /var/log/ceilometer
notification_driver=ceilometer.openstack.common.notifier.rabbit_notifier
default_notification_level=INFO
notification_topics=notifications
policy_file=policy.json
rpc_backend=ceilometer.openstack.common.rpc.impl_kombu
control_exchange=ceilometer
rabbit_host=172.16.0.254 
rabbit_port=5672
rabbit_userid=guest
rabbit_password=guest
database_connection= mongodb://ceilometer:ceilometer@172.16.0.254:27017/ceilometer
cinder_control_exchange=cinder
[publisher_rpc]
metering_secret=cdccc11cf024bd7de58e
[ssl]
[database]
[alarm]
[rpc_notifier2]
[api]
[service_credentials]
os_username=ceilometer
os_password=ceilometer
os_tenant_name=service
os_auth_url=http://172.16.0.254:5000/v2.0
[dispatcher_file]
[keystone_authtoken]
auth_host = 172.16.0.254
auth_port = 35357
auth_protocol = http
#这里写service,horizon无法加载ceilometer的信息
admin_tenant_name = admin
admin_user = admin
admin_password = password
auth_url = http://172.16.0.254:5000
[collector]
[matchmaker_ring]
[matchmaker_redis]
#+END_SRC
** 创建用户，角色，服务和endpoint
#+BEGIN_SRC sh
keystone user-create --name=ceilometer --pass=CEILOMETER_PASS --email=ceilometer@example.com
keystone user-role-add --user=ceilometer --tenant=service --role=admin

ceilometer_id=$(keystone service-create --name=ceilometer --type=metering \
--description="Ceilometer Metering Service" | awk '/ id / { print $4 }')
keystone endpoint-create \
--service-id=$ceilometer_id \
--publicurl=http://172.16.0.254:8777/ \
--internalurl=http://172.16.0.254:8777/ \
--adminurl=http://172.16.254:8777/
#+END_SRC
** 重启服务
#+BEGIN_SRC sh
cd /etc/init.d/; for i in $( ls ceilometer-* ); do sudo service $i restart; done
#+END_SRC
* 安装horizon
#+BEGIN_SRC sh
apt-get install memcached libapache2-mod-wsgi openstack-dashboard
apt-get remove --purge openstack-dashboard-ubuntu-theme
#+END_SRC
编辑/etc/openstack_dashboard/local_settings.py设置
#+BEGIN_SRC sh
OPENSTACK_KEYSTONE_DEFAULT_ROLE = "admin"
'enable_firewall' = True
TIME_ZONE = "Asia/Shanghai"
#+END_SRC
重启apache2
#+BEGIN_SRC sh
/etc/init.d/apache2 restart
#+END_SRC
浏览器访问192.168.60.108/horizon.
* 参考资料
** heat
http://openstack.redhat.com/Deploy_an_application_with_Heat \\
https://answers.launchpad.net/heat/+question/238879 \\
http://digitalsanctum.com/2013/05/01/how-to-install-openstack-heat/ \\
http://docs.openstack.org/developer/heat/getting_started/on_devstack.html \\
* 安装及使用问题
1. neutron-server无法启动，log报错AttributeError: 'NoneType' object has no attribute 'startswith' \\
   原因是CONF.api_paste_config无法找到，neutron.conf中api-paste.ini路径写错.
2. mysql报错Host 'hostname' is blocked because of many connection errors. \\
   Unblock with 'mysqladmin flush-hosts',运行 mysqladmin -uroot -p flush-hosts解决.是因为忘了建neutron数据库便启动neutron服务，造成连接问题。参考[[http://blog.itechol.com/space-33-do-blog-id-5670.html][mysql 连接出错 'mysqladmin flush-hosts']]
3. ceilometer信息界面一直显示加载中,参考https://bugs.launchpad.net/ceilometer/+bug/1232437 3楼的方法，改ceilometer.conf
   #+BEGIN_SRC sh
   admin_tenant_name = admin
   admin_user = admin
   admin_password = password
   #+END_SRC
4. 启用了namespace，建立虚拟机没有qvo,qvb等设备，虚拟机直接连在br-int上，nova.conf缺少libvirt_vif_driver=nova.virt.libvirt.vif.LibvirtHybridOVSBridgeDriver
5. l3-agent.log Failed unplugging interface 'qr-3fbe5f9e-a3',Failed unplugging interface 'qg-43105246-13' router忘了配接口
6. 删除了所有的router和network，ip netns仍旧能看到命名空间,运行neutron-netns-cleanup命令即可.
