#+SETUPFILE: ../css/level-1.orgcss
#+TITLE: 51cto访陈皓
#+DATE: 2014-01-10 10:52
#+OPTIONS: ^:{}

* 51CTO：有关您的个人成长。您感觉自己职业生涯当中有没有发展特别飞快的一段时间？
陈皓：这是个大话题。哪段时间我的个人成长最快？我入行头两年是在银行，云南工行。两年以后我去了上海，在上海我过了苦闷的两年。
* 51CTO：苦闷的两年？
陈皓：是的。就是觉得自己太差了，被人看不起。觉得自己这也弄不好，那也弄不好，而且跟这个社会差距特别大。甚至还有人羞辱我，说我这个那个没做好。还记得第一次面试的时候，到上海，就是低着头面，从头到尾都没有看面试官一眼。他问什么我都是不知道不知道……但是，那段时间是我成长最快的时候。因为那个时候，我知道自己什么也不懂，就会去学习，看书。有时候会去不停地面试，面试的时候别人问的问题你不懂，不懂你就知道自己需要学什么。所以那个时候我学的特别多，找到了一条学习的方法。现在我觉得我自己的学习能力比较强，就是受益于那个时候，学猛了。学的多了就找到了一条方法，一条最适合自己的方法。所以也就不害怕新的技术了。

首先是不害怕新的技术了。然后我知道该怎么去学习基础。一点一点的，从原理上去学。然后，再到了找工作的时候，就不害怕没工作了，因为面试后来就很容易就通过了。就是这样，我觉得这段时间是我成长最快的。

但是真正正儿八经质的提升，还是需要你有了这些基础知识，通过这些面试你只是有了块敲门砖，可以进到一些好的公司里面去，参与一些好的项目。眼界很重要。
* 51CTO：所以您觉得做好的项目，跟好的人一起共事……
陈皓：非常重要。非常重要。但是，你不能说我没有这些资源的时候我就可以什么也不懂，这就会变成这种情况：你什么也不懂，别人为啥要给你这个机会，为啥这些人会跟你一起做事。就是这样。你首先得改变自己。

还可以再补充一些。一开始别人怎么羞辱我的就不说了，基本上就是那时候别人面试完，他就跟我说，说你出来干嘛？就这个水平，你在银行里面老老实实待着就行了。“你根本就不行。”就这种感觉。然后去做项目的时候，犯了一些低级错误，还给用户造成了损失。还有很多这样的事情。就是因为有这样的一些很糟糕的经历，所以我那时候学习其实不是为别的，就是想证明自己不比别人差，自己能够学好。因为那时候从银行里出来，家里人就会觉得你出来干嘛，很多人都反对。然后前面的这些人又说，你这水平还出来，所以那时候就搞得巨难受。退也退不回去，进也找不到路，就像是爬在悬崖边上的感觉，爬在悬崖中间，上也上不去，掉下去肯定是摔死。所以只能咬着牙，学习下去。就这样，纯属意外。
* 51CTO：这，真的是想象不到……您这样厉害的人，也有这样的一段故事。
陈皓：比较励志是吧（笑）。
* 51CTO：也是给后来者们很大的信心啊。那么最后一个问题，您觉得软件行业这两年的变化大么？
陈皓：我觉得还是挺大的。这两年，尤其在互联网上面，还有风险投资，出来了Instagram这样很少的人做出来的很大的服务。互联网跟十年前的那个泡沫不一样了。还有苹果，移动互联网。目前的变化非常大，不像那个时候，我们做软件的时候，就那点东西，那么个框架，没什么好想的。现在的方向就太多了，而且发展太快。变化真的非常大。
* 51CTO：那么，现在做一个软件开发者是否更加困难了？
陈皓：我觉得倒不是。做一个软件开发者更简单了。因为现在互联网很发达，你可以找到很多共享的知识——相对于我那个时候。第一，知识你容易查到，然后社区很多，文章、分享的人也越来越多。我们那个时候没有的。上网一查，什么都没有。都得去自己琢磨，自己去调查。所以我觉得相比我们那个时候更容易了。第二，工具变多了。现在的工具比那个时候好用多了。我们那个时候就是一天到晚在vi里面，连个自动提示都没有，连个版本库管理都没有。不光工具变多，框架也多了，各种各样的编程框架。我们那时候都是生写。写JavaScript，生写，连个jQuery都没有。没有这些辅助性的、让你提高生产力的东西。J2EE那时候也没有。而且整个（开发环境）都很不成熟。一个服务器的最高配置就1GB的情况下，一个WebSphere起来就占了900多MB——这还能跑什么应用？所以只能去用最基础的系统。所以我觉得现在，无论是环境，还是开发的过程，都更规范了。以前我们做开发的时候就是，什么都不懂就上了，瞎搞，没有什么开发规范，没有人理你，反正你搞得好就搞好，搞不好就搞不好了。全靠自己，包括做测试。我觉得现在的软件开发就是，你一上去，就有好的工具，有好的知识库，有好的社区，有好的开发框架，还有好的流程，方法，甚至还有人帮你做测试，还有人告诉你应该怎么做。很幸福。现在好多人还说这个不好那个不好，开发难什么的。其实容易多了。

但是，有个东西我觉得是现在的软件开发者比我们那时候变得更难的。就是，你享福了以后，你就变懒了。对很多东西的抱怨就开始多了。我们那个时候哪有什么好抱怨的？没啥好抱怨的。干呗。有东西学就赶快学呗。现在呢，学个什么东西还挑挑拣拣的。这就好像以前我没东西吃，只有个糠吃，要是有面包有馒头，我就觉得非常非常好了。现在是，好吃的东西多了我们还学会挑食了，抱怨Java太烂，C太烂，C++太烂，或者说这个框架太差了，不好用什么的。
* 51CTO：嗯，这是一个心态上的转变。
陈皓：是的。程序员变娇气了。所以这个变难，其实是程序员们自己变娇气了（笑）。
* 51CTO：好的，那么这次问题就到这里结束。十分感谢陈皓老师接受我们的采访！
